name: blog.torresmateo.com
markdown: kramdown
highlighter: rouge
description: Rants, computational biology, and software development.
description_es: Plagueos, biología computacional, y desarrollo de software.
url: https://blog.torresmateo.com
timezone: "Europe/London"
permalink: /:title/
