name: blog.torresmateo.com
markdown: kramdown
highlighter: rouge
description: Rants, computational biology, and software development.
url: http://blog.torresmateo.com
timezone: "Europe/London"
permalink: /:title/
