name: blog.torresmateo.com
markdown: kramdown
highlighter: rouge
description: A place to find rants and some videogame dev stuff!
url: http://blog.torresmateo.com
timezone: "Europe/London"
permalink: /:title/
