name: blog.torresmateo.com
markdown: redcarpet
highlighter: true
description: A place to find rants and some videogame dev stuff!
url: http://blog.torresmateo.com
timezone: "Europe/London"
permalink: /:title/
